### ISSUE TITLE
Old ID disappears

### ISSUE THREAD

**Issue by celinedey** [GrayHatter/uTox#252] opened 2016-03-24 13:43 UTC
I've had uTox for only a few days now. I registered and sent a few friend requests. For the first 3 days, I haven't had any problems, until yesterday I opened it and I have a new ID and none of the friend requests saved. I closed out and opened it again and it's always a different ID. I have even uninstalled and reinstalled on different computers and the same thing has happened.

I'm running uTox Alpha version 0.7.0

**Comment by celinedey** [comment] 2016-03-24 15:53
on windows 7

**Comment by LittleVulpix** [comment] 2016-03-24 17:39
UAC - on or off?

**Comment by celinedey** [comment] 2016-03-24 17:42
it's on to notify me

**Comment by LittleVulpix** [comment] 2016-03-24 18:23
Try setting utox to start as admin (right click -> compatibility -> set settings for all users -> start as administrator -> ok -> ok)

**Comment by celinedey** [comment] 2016-03-24 19:26
i'm not sure if i did the right, but i went to properties of utox > compatibility and clicked run this program as an administrator and it did not work

Could you tell me where to i right click to bring up compatibility?

**Comment by LittleVulpix** [comment] 2016-03-24 19:59
That's the place. If you keep getting a new ID, it sounds like the old IDs are getting locked. Try pressing left ctrl+left shift+escape to bring up task manager and look for any "stuck" utox processes. If you see any, click them and press delete and confirm that you want to end the ask.

**Comment by celinedey** [comment] 2016-03-24 21:42
i checked the processes, and the only one running with utox is the application but thank you for trying to help me out

**Comment by lineteen** [comment] 2016-03-25 03:18
The same program when use uTox Alpha version 0.7.0 on windows 2003.
This version can not write a 'tox_save.tox' in '\Application Data\Tox' usually, just 'utox_save', if there **is** a 'tox_save.tox', it will disappear when utox exit.
It's a serious problem.

**Comment by celinedey** [comment] 2016-03-25 11:42
Yes it is a serious problem
I thought the fault was mine, something wrong with my computer. Hopefully, there will be an update ASAP

**Comment by GrayHatter** [comment] 2016-03-25 15:01
@celinedey in %APPDATA%/Tox/ there should be a file named tox_save.bak, do you see that file?

**Comment by GrayHatter** [comment] 2016-03-25 15:02
@lineteen are you sure it's disappearing when you exit uTox?

**Comment by celinedey** [comment] 2016-03-25 15:39
@GrayHatter Mine is appdata > roaming > tox & yes i have the file utox_save

**Comment by GrayHatter** [comment] 2016-03-25 16:38
@celinedey I'm not talking about the utox_save

**Comment by celinedey** [comment] 2016-03-25 16:40
@GrayHatter then i do not have that file

**Comment by lineteen** [comment] 2016-03-25 16:53
@GrayHatter  Yes, I'm sure. I tested for two days to find out why I always get a different ID when I run uTox. not alway, but 8-9/10 times. version 0.6.x not have this problem.

**Comment by TokumeiNanashi** [comment] 2016-03-26 15:42
I can confirm I've had the same problem since upgrading to 0.7.0
Back in 0.6.x every time I loaded up uTox, it prompted for a password and brought me straight to my account. After upgrading, I shut down the program and restarted it, only to find my profile and Contacts were all gone, and I was given a wholly new ToxID. Every time.

**Comment by TokumeiNanashi** [comment] 2016-03-26 16:06
In my case as well, checking AppData > Roaming > Tox, there is no tox_save.bak file there

**Comment by GrayHatter** [comment] 2016-03-26 17:17
@TokumeiNanashi what files are there?

**Comment by GrayHatter** [comment] 2016-03-26 17:20
%APPDATA%\Tox\ is what utox uses on windows.

it's usually C:\Users\username\AppData\Roming\Tox\

can you tell me every file you have in that dir @celinedey @TokumeiNanashi @lineteen

**Comment by lineteen** [comment] 2016-03-27 02:47
%APPDATA%\Tox\ 
1 avatars (folder), 
2 utox_save, 
3 12345678....90ABCDE.txt (chat record), 
4 tox_save.tox (sometimes! e.g. after add a new friend and toxed something with he/she, or some other unknown accidental, it will appear, BUT, it WILL disappear when exit uTox. More often, there is no tox_save.tox here.)
BTW, if you copy a tox_save file here, (no '.tox' suffix.) ToxID will not change when each re-open uTox. and 'tox_save' won't disappear after exit uTox too, but it's not writable, friends list cann't update.

\AppData\Roming\Tox\
1 qtox.ini, 
2 qtox.ini,lock.rmlock, 
3 qtox.log, 
4 tox_save.db,
5 tox_save.ini,
6 tox_save.lock, (disappear after exiting)
7 tox_save.tox

**Comment by TokumeiNanashi** [comment] 2016-03-27 02:55
@GrayHatter 
Under \AppData\Roaming\Tox I have...

avatars (folder, containing avatars from people on my original account's contact list)
utox_save (file)

That's all. I'm looking at the folder after a reboot without having started uTox again.

**Comment by celinedey** [comment] 2016-03-27 21:46
@GrayHatter 

AppData > Roaming > Tox there is an avatars folder and utox_save file as well

**Comment by lineteen** [comment] 2016-03-28 13:22
Hi, anyboday can send me a Utox 0.6.1? I cann't find downloads link everywhere. the version on tox.chat not available for Windows XP or 2003 (x86). TKS! (lineteen◎msn.com)

**Comment by celinedey** [comment] 2016-03-29 12:06
yes i too really need a working version of utox, if anyone has one 32 bit for windows could they send it to me? contactcelinexo@gmail.com

**Comment by chuyangguangshin** [comment] 2016-03-30 08:53
I have the same problem.

**Comment by GrayHatter** [comment] 2016-03-30 15:56
Sorry guys, I planned to have this bug fixed before monday, but life things got in the way. 

You can find old versions of µTox on the releases page on github.

**Comment by GrayHatter** [comment] 2016-03-30 16:02
https://github.com/GrayHatter/uTox/releases/tag/v0.6.1

**Comment by GrayHatter** [comment] 2016-04-01 20:10
https://build.tox.chat/job/uTox-nightly_build_windows_x86-64_debug/
this should work

**Comment by celinedey** [comment] 2016-04-01 21:57
@GrayHatter when i try to open it, it says it's not compatible for 32 bit

**Comment by GrayHatter** [comment] 2016-04-01 22:03
building a x32 version now

**Comment by GrayHatter** [comment] 2016-04-01 22:06
https://build.tox.chat/job/utox-nightly_build_windows_x86_debug/

**Comment by celinedey** [comment] 2016-04-01 22:27
@GrayHatter it works, thanks for the update

**Comment by GrayHatter** [comment] 2016-04-01 22:28
Once anyone else can confirm, I'll close this issue.

**Comment by lineteen** [comment] 2016-04-02 03:00
@GrayHatter 
It said "The procedure entry point _regdeletevalue_ could not be located in the dynamic link library _ADVAPI32.dll_" in my Windows 2003 x32 version when I run the installer. Just like the version download from tox.chat. I remember 0.6.1 is good.

**Comment by GrayHatter** [comment] 2016-04-02 03:05
@lineteen hold on I'll build you another exe

**Comment by GrayHatter** [comment] 2016-04-02 03:08
https://build.tox.chat/job/uTox-nightly-FOR-WIN-XP_build_windows_x86_debug/

**Comment by TokumeiNanashi** [comment] 2016-04-02 04:54
@GrayHatter utox-nightly_build_windows_x86_debug works for me. User ID persists after shut-down/restart of the program. There are some other, separate issues with it, but those probably deserve their own thread I imagine.

**Comment by TokumeiNanashi** [comment] 2016-04-02 05:12
For reference, the issues I'm having with the 0.7.1 alpha is exactly the same as this:
https://github.com/GrayHatter/uTox/issues/259

**Closed** 2016-04-02 05:18 UTC
Labels: bug, pla:windows, pri:critical, pri:high
