### ISSUE TITLE
dpi bug

### ISSUE THREAD

**Issue by gemaarta** [GrayHatter/uTox#427] opened 2016-09-03 15:09 UTC
![2016-09-03 18_05_17-utox alpha version _ 0 9 7](https://cloud.githubusercontent.com/assets/19753678/18225694/5b98a9ac-7201-11e6-9f3b-253fdf8528fb.png)

**Comment by tsudoko** [comment] 2016-09-03 15:32
Duplicate of #351

**Closed by tsudoko** 2016-09-03 15:32 UTC
Labels: bug, duplicate
