### ISSUE TITLE
Bottom elements on the friend panel are inactive while panel does  not fit in the window

### ISSUE THREAD

**Issue by atgote** [GrayHatter/uTox#242] opened 2016-03-13 19:07 UTC
Platform Linux x64 (Slackware 14.1), XFCE.

When friends panel does not fit in the window the bottom elements become inactive (impossible to click on).

![inactive-utox](https://cloud.githubusercontent.com/assets/3784291/13730695/dc0e02ca-e95e-11e5-8018-85ea2f45b3cd.png)
- on this screenshot the field inside red rectangle becomes inactive. The Groupbot can be clicked on the top, but on the bottom is inactive. It seems like the height of inactive zone is equal to the height of the hidden zone in the top of friends panel.

**Comment by tsudoko** [comment] 2016-03-13 19:26
Can reproduce

**Comment by GrayHatter** [comment] 2016-03-13 21:08
breaking commit should be this one https://github.com/GrayHatter/uTox/commit/1ce9a16aeb24a0b4664df81607d302b302e4d000#diff-da5a29ba66a5dcba9063909a960a06bd

The issue is how mouse and UI distance/position is calculated by the different systems, the broken box is about 5px on windows, and 15 on cocoa.

**Comment by GrayHatter** [comment] 2016-03-15 23:35
nope the bug is different... than I thought

**Comment by GrayHatter** [comment] 2016-03-18 21:01
fixed in msg-refactor

**Closed** 2016-03-20 21:52 UTC
Labels: bug, cat:user_interface
