### ISSUE TITLE
b_name and b_statusmsg too wide on Linux

### ISSUE THREAD

**Issue by Doom032** [GrayHatter/uTox#64] opened 2015-11-21 16:10 UTC
My problem:

First, when I hover over the status button, I can see my name and status message being highlighted when I hover over around respective Y values. This happens even if my name and status message are minimal size(like "a").

Also, because button_name is checked for click events before button_status, when I click the status button at the Y value of my name, I don't change my status, but instead get taken to the name changing form in the settings. Really annoying.

I can't reproduce this on Windows, but when testing on Wine with the name "WineDoom", the b_name is actually too small. If I hover over the right half of the "m", the text doesn't get highlighted, and clicking does nothing.

I see this in ui.c:
```c
            .width  = textwidth(self.name, self.name_length) - 4 * SCALE,
```

Could it be that textwidth is broken?

**Comment by tsudoko** [comment] 2015-11-21 17:06
Can reproduce, reported this in #3.

**Comment by GrayHatter** [comment] 2015-11-21 17:33
Yeah, there's something wrong with how it parses the string, the last time I looked into it. That's the reason #3 is still open, I can't find a simple solution without rewriting the whole thing.

Perhaps a quick fix would be to set it to a fixed width?

**Comment by Doom032** [comment] 2015-11-21 18:35
Oh sorry, I didn't notice #3 was about this. Yeah, fixed width for the buttons would fix this annoyance at least. Don't know what other places textwidth is used. I'd think it'd be used for tooltips and the message log, but those are both working fine.

**Comment by GrayHatter** [comment] 2015-12-19 01:16
I'm closing this in favor of #3

**Closed by GrayHatter** 2015-12-19 01:16 UTC
Labels: bug, cat:user_interface, duplicate
