### ISSUE TITLE
Profile / ID disappearing

### ISSUE THREAD

**Issue by avja55** [GrayHatter/uTox#188] opened 2016-01-30 08:38 UTC
{ Win7 x64, uTox 0.5.0 } 

This is the second time I start uTox on this computer and end up with a fresh ID instead of my old one. Not after a crash or anything like that, it just simply disappeared.
Since I have two laptops and another uTox account there, I went and added that one first with my new ID. For some reason the messages I had sent to it before showed up on my end as if I was using the same account as before, while on the other end it showed up as a brand new contact, since it WAS a different ID. While the older account was still there. (Probably something to do with the fact that the message logs are saved?)

Same thing when I added my other friends later, but I'm more worried about my ID disappearing once again. So I'd like some help to know what's going on, or if it's just something I should overlook when using CCleaner.

P.S. Read the forums and saw something about a tox save but that does nothing, the only one I had was from qTox (months ago) and the uTox one didn't work apparently. Since there's no way to import accounts using ToxID+password (at least I haven't seen one) this is even more annoying.

EDIT: Just making sure, it's not invisible like #187 . It just vanishes and I get a fresh new one for some reason.

**Comment by GrayHatter** [comment] 2016-01-30 16:52
You're using an outdated version of uTox upgrade to 0.5.1

I'm not convinced that was the root cause so I'm going to leave thin open for now. At least untitl I can get some new information

**Comment by tsudoko** [comment] 2016-01-30 18:32
Not sure what the cause could be. You might want to back up your profile, it's located in `%LOCALAPPDATA%\tox\tox_save.tox`.

**Comment by avja55** [comment] 2016-01-30 18:41
Yeah I'm definitely backing up my profile now, but I'm wondering what the cause of it could've been.

I suspected it to be CCleaner messing something up, but I just did some clearing with it on the 0.5.0 uTox version on the other laptop and on the upgraded 0.5.1 version on this laptop, then restarted both of them.
No changes on either, and the 0.5.0 one still has its old ID, no fresh new one assigned. I haven't installed or uninstalled any other software lately so I don't think that's what messed it up. Either way I'll keep an eye out for everything in case this happens again.

**Comment by GrayHatter** [comment] 2016-01-30 18:52
This is not the first time I've heard about losing profiles. It's
clobbering the backup when it does the atomic save so I think fixing that
is the fastest way to solve this problem.

**Comment by ingvar1995** [comment] 2016-01-31 20:19
utox sometimes doesn't save tox_save.tox for some reason. is it windows only bug?

**Comment by GrayHatter** [comment] 2016-01-31 20:37
that shouldn't be true

**Comment by ingvar1995** [comment] 2016-01-31 20:41
Test 93
tox_save.tox 15221
utox_save 84
Test 94
tox_save.tox.tmp 15260
utox_save 84
Test 95
tox_save.tox 999
utox_save 84
i got it during testing. file name - size in bytes.

**Comment by GrayHatter** [comment] 2016-01-31 20:44
okay that's not right... ill do some testing once toxcore is un-rip

**Comment by ingvar1995** [comment] 2016-01-31 20:46
that's old problem but I thought it was fixed.

**Comment by GrayHatter** [comment] 2016-01-31 20:47
do you remember what fixed it last time?

**Comment by ingvar1995** [comment] 2016-01-31 20:48
no, sorry. last time i lost my profile because of it more than year ago. i will try to find this bug tomorrow using tests

**Comment by Z5he2h7D09OD** [comment] 2016-02-23 21:10
i just had this happen yesterday, Windows 10, utox 0.5.1

my profile and friends are all gone, i ran CCleaner, but it doesnt even list tox in the applications that it touches

i also can confirm another person stating an older version of either qtox or utox did let you have mutliple userID's and swap between them or load them

**Comment by avja55** [comment] 2016-02-23 22:48
I guess I should update this as well. I tried turning off my computer through brute force and closing uTox's service through task manager a few times since I made this thread to see if it was a consequence of it not saving the profile before closing but it remained intact on both of my laptops running W7 and utox 0.5.1.

**Comment by Z5he2h7D09OD** [comment] 2016-02-25 01:29
avja55 did you run CCleaner too?

cause that's the one similarities to the OP issue

either way im probably not going to continue using it till another point-version is released cause this is clearly still in alpha as it states, even tho i never had this issue with the prior versions (on linux atleast)

**Comment by avja55** [comment] 2016-02-25 02:30
I'm the OP. I tried CCleaner on both of them again and nothing happened. 
Just for the sake of helping I ran it again with them running, with them not running, and after they get force closed. Still no change.
I am suspecting however that it might have had something to do with having an older version of another Tox client installed at the time and since they both share the same folder for saves maybe it messed it up on a very specific occasion (or maybe something messed with that folder after qtox or whatever not being used for so long), was that also the case for you?

**Comment by Z5he2h7D09OD** [comment] 2016-02-25 23:53
utox 0.5.0 was the only version i had installed, i didnt install the .1 till it was mentioned ITT, after the fact of the ID being reset, after using utox for a few days in a row after install.

thats how i found this thread cause i had no idea what caused it.

**Comment by avja55** [comment] 2016-03-03 01:28
And it happens again on the 0.6.1, still no idea what exactly caused it sorry. 
It might be what @ingvar1995 said about the tox save. After it happened I kept opening it and exiting for a while (only changing the name and status), sometimes waiting until it was online before exiting while keeping the Roaming/tox folder open. And just like magic sometimes tox_save would disappear and leave only the tox_save.tox.tmp instead.

Kept repeating that process for about 50ish times and profile loss happened 3 times. I'm not sure if this is any help but I hope it helps.

**Comment by GrayHatter** [comment] 2016-03-03 13:01
Is this on windows on Linux?

**Comment by avja55** [comment] 2016-03-04 01:20
Same stuff, still on W7.

**Comment by GrayHatter** [comment] 2016-03-11 05:39
so this just happened to me, it's going to get fixed  in 0.7 release

**Comment by GrayHatter** [comment] 2016-03-20 04:50
so this is fixed in develop I think. I'm going to close this, Anyone who's following this should still keep a backup of their profile, but it should be fixed.

As always, ping me if you have any issues!

**Closed by GrayHatter** 2016-03-20 04:50 UTC
Labels: bug, pla:windows, pri:critical, pri:high, regression

**Comment by Ace17** [comment] 2018-05-17 08:30
My profile just disappeared.
Running GNU/Linux, uTox version: 0.17.0
