### ISSUE TITLE
white line instead of system tray icon in MATE

### ISSUE THREAD

**Issue by akhilman** [GrayHatter/uTox#16] opened 2015-10-11 08:38 UTC
White line instead of system tray icon in MATE on Debian stretch.
Line acts like a tray icon, I still can click it to hide and unhide uTox window.
branch is lintray_bg
![utox tray icon](https://cloud.githubusercontent.com/assets/180812/10416030/ccda76ba-7025-11e5-891e-3bba29c41941.png)

**Comment by GrayHatter** [comment] 2015-10-11 16:41
@akhilman are you on the lintray_bg branch?

**Comment by akhilman** [comment] 2015-10-11 22:29
@GrayHatter 
```
$ git clone -b lintray_bg https://github.com/GrayHatter/uTox.git uTox-lintray_bg
$ cd uTox-lintray_bg
$ git status
On branch lintray_bg
Your branch is up-to-date with 'origin/lintray_bg'.
nothing to commit, working directory clean
$ make
$ ./utox
```
and no icon

**Comment by GrayHatter** [comment] 2015-10-11 23:03
can you gist me the output?

**Comment by akhilman** [comment] 2015-10-11 23:27
@GrayHatter this one?
```
AL lib: (WW) FreeContext: (0x7fbf3400d610) Deleting 32 Source(s)
AL lib: (WW) FreeDevice: (0x7fbf3400df50) Deleting 1 Buffer(s)
Read 84 bytes (/home/ildar/.config/tox/utox_save)
2
have GTK
Read 11620 bytes (/home/ildar/.config/tox/tox_save.tox)
new tox object ipv6: 1 udp: 1 proxy: 0  0
File not found (/home/ildar/.config/tox/56A1ADE4B65B86BCD51CC73E2CD4E542179F47959FE3E0E21B4B0ACDADE51855.txt)
File not found (56A1ADE4B65B86BCD51CC73E2CD4E542179F47959FE3E0E21B4B0ACDADE51855.txt)
Meta Data not found (/home/ildar/.config/tox/56A1ADE4B65B86BCD51CC73E2CD4E542179F47959FE3E0E21B4B0ACDADE51855.fmetadata)
File not found (/home/ildar/.config/tox/8A20305B48769AF9FFDE2165A08C8AADF322FFD690D07C238F48A3A526E9B32F.txt)
File not found (8A20305B48769AF9FFDE2165A08C8AADF322FFD690D07C238F48A3A526E9B32F.txt)
Meta Data not found (/home/ildar/.config/tox/8A20305B48769AF9FFDE2165A08C8AADF322FFD690D07C238F48A3A526E9B32F.fmetadata)
File not found (/home/ildar/.config/tox/3CF551AABD8393E7C7F6B9B1E6C6E98568E252578ED0FF10DE08FECC4D5C7D3E.txt)
File not found (3CF551AABD8393E7C7F6B9B1E6C6E98568E252578ED0FF10DE08FECC4D5C7D3E.txt)
Meta Data not found (/home/ildar/.config/tox/3CF551AABD8393E7C7F6B9B1E6C6E98568E252578ED0FF10DE08FECC4D5C7D3E.fmetadata)
Read 7388 bytes (/home/ildar/.config/tox/avatars/1F54C58ECDAE32226C169755478381AFF21AFD972D1C3C8EDA35FA6905FFFC09.png)
File not found (/home/ildar/.config/tox/1F54C58ECDAE32226C169755478381AFF21AFD972D1C3C8EDA35FA6905FFFC09.txt)
File not found (1F54C58ECDAE32226C169755478381AFF21AFD972D1C3C8EDA35FA6905FFFC09.txt)
Meta Data not found (/home/ildar/.config/tox/1F54C58ECDAE32226C169755478381AFF21AFD972D1C3C8EDA35FA6905FFFC09.fmetadata)
Tox ID: 66E9F8450D0380B76456DC9572D111D9257C55455034F859CCD8AC40EC20444EF21C5B0D7160
Read 7992 bytes (/home/ildar/.config/tox/avatars/66E9F8450D0380B76456DC9572D111D9257C55455034F859CCD8AC40EC20444E.png)
Tox Avatar Hash: FD87BF6FB262E60A39344489B3AE99289BC3DA0301F2286286101351D42A7EE3
Audio Filtering enabled in this build
frame size: 960
Toxav thread init
desktop: 2646 1024
Input Device List:
ClearChat Pro USB Аналоговый моно
Monitor of ClearChat Pro USB Аналоговый стерео
iSlim 2020AF Аналоговый моно
Monitor of Встроенное аудио Аналоговый объёмный 4.0
Monitor of SB Audigy Аналоговый стерео
SB Audigy Аналоговый стерео
Loaded font /usr/share/fonts/truetype/roboto/Roboto-Regular.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/roboto/Roboto-Bold.ttf 0 30 -7
Output Device List:
Встроенное аудио Аналоговый объёмный 4.0
ClearChat Pro USB Аналоговый стерео
SB Audigy Аналоговый стерео
Loaded font /usr/share/fonts/truetype/roboto/Roboto-Bold.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/roboto/Roboto-Regular.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/roboto/Roboto-Regular.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/roboto/Roboto-Regular.ttf 0 30 -7
filter audio on
Loaded font /usr/share/fonts/truetype/roboto/Roboto-Regular.ttf 0 30 -7
Video size: 640 480
Loaded font /usr/share/fonts/truetype/roboto/Roboto-Bold.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/roboto/Roboto-Bold.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/roboto/Roboto-Regular.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/roboto/Roboto-Regular.ttf 0 30 -7
Loaded font /usr/share/fonts/truetype/roboto/Roboto-Regular.ttf 0 30 -7
set audio in
resize
expose
set audio out
Writing uTox Save	::
Writing tox_save to: /home/ildar/.config/tox/tox_save.tox.tmp
Toxav thread die
Saved data
CHMOD: success
av_thread exit, tox thread ending
clean exit
```

**Comment by GrayHatter** [comment] 2015-10-11 23:45
Google suggests that mate resizes then forgets to tell the icon window.
I'll try to get a fix out soon, one that will delay showing the window
until after we've confirmed the embed.

**Comment by GrayHatter** [comment] 2015-12-27 00:35
This should be fixed in master already @akhilman could you confirm that this is fixed?

**Closed by GrayHatter** 2015-12-27 00:35 UTC
Labels: bug, cat:user_interface

**Comment by akhilman** [comment] 2015-12-27 03:32
Tray icon shows up nicely in i3wm, but after that uTox from master eats
all memory and makes whole system hang.

**Comment by akhilman** [comment] 2015-12-27 03:41
i will setup VirtualBox with Debian Sid and Mate and try agait later.

**Comment by GrayHatter** [comment] 2015-12-27 04:18
@akhilman I can't duplicate that at all, where'd you get your version of µTox?

I'd like to find this issue, come find me in #tox on freenode

**Comment by cebe** [comment] 2015-12-28 02:17
> but after that uTox from master eats all memory and makes whole system hang.

maybe related to #82?

does your system have a camera? if so, does it solve the issue, if you unplug it?

**Comment by akhilman** [comment] 2015-12-28 07:11
Yes system have a camera, but after full system update and clean rebuild of tox core and utox I can not more reproduce memory leaks.

**Comment by MartinX3** [comment] 2017-01-13 11:37
#612 
Still exists! Still open!
Since years for me.
